//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBOperation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Despatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Despatch()
        {
            this.DespatchItems = new HashSet<DespatchItem>();
        }
    
        public int Id { get; set; }
        public int OutwardId { get; set; }
        public string DespatchNo { get; set; }
        public System.DateTime DespatchDate { get; set; }
        public string LRNumber { get; set; }
        public string PaymentStatus { get; set; }
        public string TransportBy { get; set; }
        public string ShipToCity { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual Outward Outward { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DespatchItem> DespatchItems { get; set; }
    }
}
