//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBOperation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.ProjectClients = new HashSet<ProjectClient>();
        }
    
        public int Id { get; set; }
        public string ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
        public int ClientCompany { get; set; }
        public int ProjectLead { get; set; }
        public decimal EstimatedBudget { get; set; }
        public decimal TotalAmountSpent { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EstimatedEndDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectClient> ProjectClients { get; set; }
        public virtual ProjectStatu ProjectStatu { get; set; }
        public virtual User User { get; set; }
    }
}
