//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBOperation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.SaleProducts = new HashSet<SaleProduct>();
        }
    
        public int Id { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int Status { get; set; }
        public string AnticipatedClosing { get; set; }
        public int NoOfFollowUps { get; set; }
        public Nullable<System.DateTime> NextFollowUpDate { get; set; }
        public int RepresentativeId { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleProduct> SaleProducts { get; set; }
        public virtual SalesStatu SalesStatu { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
