//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBOperation
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRM_OutwardStock
    {
        public int OutwardId { get; set; }
        public string InvoiceNumber { get; set; }
        public System.DateTime OutwardDate { get; set; }
        public bool IsActive { get; set; }
        public string CustomerInformation { get; set; }
    }
}
